server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Sintexer/config-serverito.git

management:
  endpoints:
    web:
      exposure:
        include: "*"