server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Sintexer/config-serverito.git
          default-label: master
          search-paths:
            - "{application}"
random:
  env: 1

management:
  endpoints:
    web:
      exposure:
        include: "*"